# Generated by Django 5.1.1 on 2024-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('open', models.DateField()),
                ('close', models.DateField()),
                ('coffee', models.IntegerField(choices=[(1, 'onestar'), (2, 'twostar'), (3, 'threestar'), (4, 'fourstar'), (5, 'fivestar')], default=0)),
                ('wifi', models.IntegerField(choices=[(1, 'onestar'), (2, 'twostar'), (3, 'threestar'), (4, 'fourstar'), (5, 'fivestar')], default=0)),
                ('powersockets', models.IntegerField()),
            ],
        ),
    ]
