# Generated by Django 5.1.1 on 2024-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='close',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='open',
            field=models.TimeField(),
        ),
    ]
