# Generated by Django 5.1.1 on 2024-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_alter_cafe_close_alter_cafe_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='coffee',
            field=models.IntegerField(choices=[(1, '☆'), (2, '☆☆'), (3, '☆☆☆'), (4, '☆☆☆☆'), (5, '☆☆☆☆☆')], default=0),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='wifi',
            field=models.IntegerField(choices=[(1, '☆'), (2, '☆☆'), (3, '☆☆☆'), (4, '☆☆☆☆'), (5, '☆☆☆☆☆')], default=0),
        ),
    ]
