# Generated by Django 5.1.1 on 2024-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_alter_cafe_coffee_alter_cafe_powersockets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='powersockets',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'tow'), (3, 'three'), (4, 'four'), (5, 'five')], default=0),
        ),
    ]
