# Generated by Django 5.1.1 on 2024-09-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_alter_cafe_powersockets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='location',
            field=models.TextField(max_length=50),
        ),
    ]
